apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gutenberg-search-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/satomichi/k8s_practice_sample.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: gutenberg-search-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10
