apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: satomichi

resources:
- ../../base

patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: backend
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: frontend

images:
- name: ghcr.io/satomichi/k8s-practice-frontend
  newTag: latest
- name: ghcr.io/satomichi/k8s-practice-backend
  newTag: latest

labels:
- pairs:
    environment: satomichi

namePrefix: ""
