apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: satomichi

resources:
- ../../base
- ingress.yaml

patches:
- path: backend-patch.yaml
  target:
    kind: Deployment
    name: backend
- path: frontend-patch.yaml
  target:
    kind: Deployment
    name: frontend

images:
- name: ghcr.io/satomichi/k8s-practice-backend
  newName: ghcr.io/satomichi/k8s-practice-backend
  newTag: cb125cb
- name: ghcr.io/satomichi/k8s-practice-frontend
  newName: ghcr.io/satomichi/k8s-practice-frontend
  newTag: cb125cb

labels:
- pairs:
    environment: satomichi
