apiVersion: apps/v1
kind: Deployment
metadata:
  name: gutenberg-frontend
  namespace: satomichi
  labels:
    app.kubernetes.io/name: gutenberg-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: gutenberg-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gutenberg-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/SatoMichi/k8s-practice-frontend:latest
        env:
        - name: BACKEND_HOST
          value: "gutenberg-backend"
        - name: BACKEND_PORT
          value: "8000"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gutenberg-backend
  namespace: satomichi
  labels:
    app.kubernetes.io/name: gutenberg-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: gutenberg-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gutenberg-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/SatoMichi/k8s-practice-backend:latest
        ports:
        - containerPort: 8000
