apiVersion: v1
kind: Service
metadata:
  name: gutenberg-frontend
  namespace: satomichi
spec:
  selector:
    app.kubernetes.io/name: gutenberg-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gutenberg-backend
  namespace: satomichi
spec:
  selector:
    app.kubernetes.io/name: gutenberg-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
