name: Frontend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths: [ 'frontend/**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Run tests
      run: |
        cd frontend
        npm test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Clear Docker cache
      run: |
        docker system prune -f
        docker builder prune -f
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Debug - Show variables
      run: |
        echo "GitHub Actor: ${{ github.actor }}"
        echo "GitHub Repository Owner: ${{ github.repository_owner }}"
        echo "Repository: ${{ github.repository }}"
        echo "Current timestamp: $(date)"
        echo "Lowercase actor: $(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')"
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/k8s-practice-frontend:latest
          ghcr.io/${{ github.repository_owner }}/k8s-practice-frontend:main
          ghcr.io/${{ github.repository_owner }}/k8s-practice-frontend:${{ github.sha }}
        labels: |
          org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=${{ github.repositoryUrl }}
          org.opencontainers.image.title=k8s_practice_sample
          org.opencontainers.image.url=${{ github.repositoryUrl }}
          org.opencontainers.image.version=main
        no-cache: true

# Updated Thu Jun 19 17:10:00 JST 2025 - Fix Container Registry authentication and dynamic repository names
