name: GitOps Deploy

on:
  # workflow_run:
  #   workflows: ["Backend CI/CD", "Frontend CI/CD"]
  #   types:
  #     - completed
  #   branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-image-tags:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup kustomize
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        sudo mv kustomize /usr/local/bin/

    - name: Update image tags
      run: |
        # 最新のコミットハッシュを取得
        COMMIT_SHA=$(git rev-parse --short HEAD)
        echo "Updating image tags to: $COMMIT_SHA"
        
        # satomichi環境のイメージタグを更新
        cd k8s/overlays/satomichi
        kustomize edit set image ghcr.io/satomichi/k8s-practice-frontend=ghcr.io/satomichi/k8s-practice-frontend:$COMMIT_SHA
        kustomize edit set image ghcr.io/satomichi/k8s-practice-backend=ghcr.io/satomichi/k8s-practice-backend:$COMMIT_SHA
        
        # 変更内容を確認
        cd ../..
        git status
        git diff

    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git diff --cached --quiet || git commit -m "Update image tags to ${{ github.sha }}"
        git push
